### ISSUE TITLE
Access Wallace lab data store

### ISSUE THREAD

**Issue by DimmestP** [JingQiChong/Ssd1_CRACanalysis_2020#2]
- check that Edward has granted you permission to access the lab datastore (where sequencing data is held)

**Comment by ewallace** [comment]
I have given permission, but I don't know if @JingQiChong has succeeded in accessing yet.

**Comment by JingQiChong** [comment]
I still failed to access the datastore, shall I email Shaun, @ewallace ?

**Comment by JingQiChong** [comment]
I managed to access the lab datastore. Turned out I have been using the wrong command line because I did not know there is a slight difference in how to access datastore in Bifx server.
