### ISSUE TITLE
Create a profile on the lab website

### ISSUE THREAD

**Issue by DimmestP** [JingQiChong/Ssd1_CRACanalysis_2020#3]
- All members of the Wallace lab have a team profile on the [lab website](https://ewallace.github.io/team/)
- You can also find the [guide for new members](https://ewallace.github.io/manual/newstart) of the lab on the website
- There is help for how to add posts the to lab website on the github repo [README file](https://github.com/ewallace/ewallace.github.io/blob/master/README.md)
- create your team post in a similar style to [Edward's](https://github.com/ewallace/ewallace.github.io/blob/master/team/_posts/2017-12-13-edward-wallace.md) and add it to the teams/_posts folder (preferably with a photo of yourself in the assets/images/team/ folder

**Comment by JingQiChong** [comment]
17th Jan 2022: Created a team profile for myself via branch 'JingQi-Profile' and submitted a pull request.

**Comment by ewallace** [comment]
I accepted this pull request. https://github.com/ewallace/ewallace.github.io/pull/101
